[package]
name = "bevy_motiongfx"
description = "An implementation of the MotionGfx framework for Bevy."
exclude = ["/assets/", "/examples/"]
keywords = ["motion", "animation", "procedural", "bevy", "plugin"]
categories = ["no-std", "multimedia", "graphics", "visualization", "gui"]
readme = "./README.md"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
# motiongfx
motiongfx = { workspace = true }
motiongfx_scene = { workspace = true, optional = true }

# bevy
bevy_ecs = { workspace = true }
bevy_app = { workspace = true }
bevy_platform = { workspace = true }
bevy_derive = { workspace = true }
bevy_math = { workspace = true }
bevy_time = { workspace = true }
bevy_asset = { workspace = true, optional = true }
bevy_transform = { workspace = true, optional = true }
bevy_color = { workspace = true, optional = true }
bevy_reflect = { workspace = true, optional = true, features = ["uuid"] }

# other
serde = { workspace = true, features = ["derive"] }
sparse_map = { workspace = true, features = ["serde"], optional = true }
ron = { workspace = true, optional = true }

[dev-dependencies]
bevy = { workspace = true, features = ["bevy_pbr"] }

[lints]
workspace = true

[features]
default = ["std", "asset", "transform", "color"]
std = ["motiongfx/std", "motiongfx_scene/std", "bevy_ecs/std", "bevy_app/std", "bevy_platform/std", "bevy_time/std"]
asset = ["dep:bevy_asset"]
transform = ["dep:bevy_transform"]
color = ["dep:bevy_color"]
scene = [
    "dep:motiongfx_scene",
    "dep:sparse_map",
    "dep:ron",
    "dep:bevy_reflect",
    "bevy_math/serialize",
    "bevy_transform/bevy_reflect",
    "asset",
    "transform",
]
