//! Turns a track's composition tree ([`Track::meta`]) into the
//! timeline view: clip boxes, group containers, and collapse toggles.
//!
//! [`Track::meta`]: bevy_motiongfx::prelude::Track::meta

use core::hash::{Hash, Hasher};
use std::hash::DefaultHasher;

use bevy::feathers::constants::icons;
use bevy::picking::events::{Click, Pointer};
use bevy::platform::collections::HashSet;
use bevy::prelude::*;
use bevy_motiongfx::prelude::*;

use crate::scene::{Playhead, TimelineContent};
use motiongfx_editor_ui::{
    ActionBox, GroupBox, GroupToggle, clip_box, group_box,
    group_toggle,
};
use crate::{
    EditorState, PIXELS_PER_SECOND, ROW_HEIGHT, ROW_STRIDE,
    TRACK_TOP_PADDING,
};

/// Size of the chevron toggle shown on an expanded group.
const CHEVRON_SIZE: f32 = 16.0;
/// Breathing room between a group container and the boxes inside it.
const GROUP_PAD: f32 = 5.0;

/// Fills in the timeline view once a timeline exists. Runs every
/// frame until it finds one (the timeline is built in the user's
/// `Startup`), then latches via [`EditorState::built`].
///
/// Renders the first track's composition tree ([`Track::meta`]): each
/// action is a clip box positioned by its absolute start/duration,
/// and concurrent groups (all / any / flow) get a container behind
/// them.
///
/// [`Track::meta`]: bevy_motiongfx::prelude::Track::meta
#[expect(clippy::type_complexity)]
pub(crate) fn build_timeline_view(
    mut commands: Commands,
    mut state: ResMut<EditorState>,
    manager: Res<MotionGfxManager>,
    q_timelines: Query<&TimelineId>,
    mut q_nodes: Query<&mut Node, Without<Playhead>>,
    q_content: Query<Entity, With<TimelineContent>>,
    // Everything generated by a previous build, to tear down on
    // rebuild.
    q_generated: Query<
        Entity,
        Or<(With<ActionBox>, With<GroupBox>, With<GroupToggle>)>,
    >,
) {
    if state.built {
        return;
    }

    let Some(timeline_id) = q_timelines.iter().next().copied() else {
        return;
    };
    let Some(timeline) = manager.get_timeline(&timeline_id) else {
        return;
    };
    // Focus on the first track only.
    let Some(track) = timeline.tracks().first() else {
        return;
    };
    let Ok(content) = q_content.single() else {
        return;
    };

    // Tear down the previous generation (keeps the playhead thumb).
    for entity in &q_generated {
        commands.entity(entity).despawn();
    }

    // Walk the composition tree into flat placement lists.
    let mut layout = TimelineLayout::new(&state.collapsed);
    let rows = layout.place(track.meta(), 0, &mut 0, true);

    let duration = track.duration();
    let content_width = (duration * PIXELS_PER_SECOND).max(1.0);
    let content_height =
        TRACK_TOP_PADDING * 2.0 + rows as f32 * ROW_STRIDE;

    // Size the track to the composition; scrubbing maps cursor x onto
    // this span via `PIXELS_PER_SECOND`.
    if let Ok(mut node) = q_nodes.get_mut(content) {
        node.width = Val::Px(content_width);
        node.min_width = Val::Px(content_width);
        node.height = Val::Px(content_height);
        node.min_height = Val::Px(content_height);
    }

    // Containers first, then clips, then toggles, so each paints over
    // the previous. These use `ChildOf` rather than a `Children [..]`
    // list on `content`: applying a scene with `Children` writes a
    // fresh (empty) collection onto the target first, which would
    // orphan the playhead thumb already parented here.
    for g in &layout.groups {
        commands.spawn_scene(bsn! {
            group_box(g.left, g.top, g.width, g.height)
            ChildOf({content})
        });
    }
    for c in &layout.clips {
        commands.spawn_scene(bsn! {
            clip_box(
                c.left, c.top, c.width, ROW_HEIGHT, c.color, c.label,
            )
            ChildOf({content})
        });
    }
    for t in &layout.toggles {
        commands.spawn_scene(bsn! {
            group_toggle(
                t.gid, t.left, t.top, t.width, t.height, t.icon,
                &t.label, t.bg,
            )
            ChildOf({content})
            on(on_group_toggle)
        });
    }

    state.timeline = Some(timeline_id);
    state.duration = duration;
    state.built = true;
}

/// Rebuild the view when the dock re-materializes the timeline window
/// (e.g. after its tab is dragged to another area): the fresh
/// [`TimelineContent`] starts empty, so the latched `built` must
/// clear.
pub(crate) fn on_timeline_content_added(
    _add: On<Add, TimelineContent>,
    mut state: ResMut<EditorState>,
) {
    state.built = false;
}

/// Toggle a group's collapsed state and rebuild the view. Attached to
/// each toggle; the click may hit a child (icon/label), so walk up.
pub(crate) fn on_group_toggle(
    mut click: On<Pointer<Click>>,
    q_toggle: Query<&GroupToggle>,
    q_parents: Query<&ChildOf>,
    mut state: ResMut<EditorState>,
) {
    click.propagate(false);
    let mut entity = click.entity;
    let gid = loop {
        if let Ok(GroupToggle(gid)) = q_toggle.get(entity) {
            break *gid;
        }
        let Ok(parent) = q_parents.get(entity) else {
            return;
        };
        entity = parent.parent();
    };
    if !state.collapsed.remove(&gid) {
        state.collapsed.insert(gid);
    }
    // Force `build_timeline_view` to rebuild with the new state.
    state.built = false;
}

/// A clip box to spawn, resolved from a [`FragmentKind::Leaf`].
struct ClipPlacement {
    left: f32,
    top: f32,
    width: f32,
    color: Color,
    label: &'static str,
}

/// A group container to spawn, resolved from a concurrent group node.
struct GroupPlacement {
    left: f32,
    top: f32,
    width: f32,
    height: f32,
}

/// A collapse toggle to spawn for a concurrent group.
struct TogglePlacement {
    gid: usize,
    left: f32,
    top: f32,
    width: f32,
    height: f32,
    /// Embedded feathers chevron icon path.
    icon: &'static str,
    label: String,
    bg: Color,
}

/// Accumulates placements while walking a [`FragmentMeta`] tree.
struct TimelineLayout<'a> {
    collapsed: &'a HashSet<usize>,
    clips: Vec<ClipPlacement>,
    groups: Vec<GroupPlacement>,
    toggles: Vec<TogglePlacement>,
}

/// Derive a stable, distinct color by hashing an id (e.g. a clip's
/// subject) into a hue.
fn hashed_color(value: impl Hash) -> Color {
    let mut hasher = DefaultHasher::new();
    value.hash(&mut hasher);
    // Normalize the 64-bit hash into [0, 1) in f64 (which keeps the
    // precision), then scale to a continuous hue. Casting the raw
    // hash to f32 and taking `% 360` instead would band into 360
    // values.
    let hue =
        (hasher.finish() as f64 / u64::MAX as f64) as f32 * 360.0;
    Color::hsl(hue, 0.6, 0.65)
}

impl<'a> TimelineLayout<'a> {
    fn new(collapsed: &'a HashSet<usize>) -> Self {
        Self {
            collapsed,
            clips: Vec::new(),
            groups: Vec::new(),
            toggles: Vec::new(),
        }
    }

    /// Place `node` starting at `base_row`, returning the rows it
    /// occupies. Sequential (`Chain`) children share a row band;
    /// concurrent (`All`/`Any`/`Flow`) children stack.
    ///
    /// `next_gid` numbers every group in pre-order (independent of
    /// collapse) so ids stay stable across rebuilds. `draw` is
    /// cleared while inside a collapsed group: descendants are
    /// still numbered but not emitted.
    fn place(
        &mut self,
        node: &FragmentMeta,
        base_row: usize,
        next_gid: &mut usize,
        draw: bool,
    ) -> usize {
        let left = node.start * PIXELS_PER_SECOND;
        let width = (node.duration * PIXELS_PER_SECOND).max(2.0);
        let top = TRACK_TOP_PADDING + base_row as f32 * ROW_STRIDE;

        match &node.kind {
            FragmentKind::Leaf { key, .. } => {
                if draw {
                    // Color by subject entity, so all of an entity's
                    // clips share a color across groups.
                    self.clips.push(ClipPlacement {
                        left,
                        top,
                        width,
                        color: hashed_color(key.subject_id()),
                        label: key.field().field_path(),
                    });
                }
                1
            }
            FragmentKind::Group {
                combinator,
                children,
            } => {
                let gid = *next_gid;
                *next_gid += 1;

                let concurrent =
                    !matches!(combinator, Combinator::Chain);
                let collapsed =
                    concurrent && self.collapsed.contains(&gid);
                let child_draw = draw && !collapsed;

                let rows = if matches!(combinator, Combinator::Chain)
                {
                    // Sequential: reuse the same band across
                    // children.
                    children
                        .iter()
                        .map(|c| {
                            self.place(
                                c, base_row, next_gid, child_draw,
                            )
                        })
                        .max()
                        .unwrap_or(1)
                } else {
                    // Concurrent: stack children onto successive
                    // rows.
                    let mut row = base_row;
                    for child in children {
                        row += self
                            .place(child, row, next_gid, child_draw);
                    }
                    (row - base_row).max(1)
                };

                // Only concurrent groups are drawn/collapsible.
                if !(draw && concurrent) {
                    return rows;
                }

                if collapsed {
                    // Whole group as one clickable summary row.
                    self.toggles.push(TogglePlacement {
                        gid,
                        left,
                        top,
                        width,
                        height: ROW_HEIGHT,
                        icon: icons::CHEVRON_RIGHT,
                        label: format!(
                            "{} x{}",
                            combinator_name(combinator),
                            children.len(),
                        ),
                        bg: Color::srgb(0.24, 0.26, 0.32),
                    });
                    return 1;
                }

                // Expanded: container behind + a chevron to collapse.
                // Pad only vertically: the horizontal extent maps to
                // time (`start`/`duration`), so inflating left/width
                // would desync the container from its clips.
                let content_height =
                    (rows - 1) as f32 * ROW_STRIDE + ROW_HEIGHT;
                self.groups.push(GroupPlacement {
                    left,
                    top: top - GROUP_PAD,
                    width,
                    height: content_height + 2.0 * GROUP_PAD,
                });
                self.toggles.push(TogglePlacement {
                    gid,
                    left,
                    top,
                    width: CHEVRON_SIZE,
                    height: CHEVRON_SIZE,
                    icon: icons::CHEVRON_DOWN,
                    label: String::new(),
                    bg: Color::srgba(0.0, 0.0, 0.0, 0.35),
                });
                rows
            }
        }
    }
}

fn combinator_name(combinator: &Combinator) -> &'static str {
    match combinator {
        Combinator::Chain => "chain",
        Combinator::All => "all",
        Combinator::Any => "any",
        Combinator::Flow(_) => "flow",
    }
}
