[package]
name = "bevy_examples"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
readme.workspace = true

[dependencies]
bevy_motiongfx = { workspace = true }
bevy = { workspace = true }

[dev-dependencies]
bevy = { workspace = true, features = [
  "dynamic_linking",
  "multi_threaded",
  "bevy_log",
  "bevy_color",
  "bevy_pbr",
  "bevy_post_process",
  "hdr",
  "tonemapping_luts",
  "zstd_rust",
] }

[lints]
workspace = true
