[package]
name = "bevy_examples"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
readme.workspace = true
publish = false

[dependencies]
bevy_motiongfx = { workspace = true }
bevy = { workspace = true }

[dev-dependencies]
bevy = { workspace = true, default-features = true }

[lints]
workspace = true
